version: '2.2'

services:
    web:
        build:
            context: ./images/nginx
        ports:
            - 80:80
            - 443:443
        environment:
            ADMIN_URL: admin
            ADMIN_LOCALE: pt_BR
            APPLICATION_MODE: developer
            UPDATE_URLS: enabled
        volumes:
            - ./logs/nginx:/var/log/nginx
            - ./config/nginx/conf.d/magento.conf:/etc/nginx/conf.d/magento.conf
            - ./config/nginx/conf.d/project.conf:/etc/nginx/conf.d/project.conf
        volumes_from:
            - php
        depends_on:
            - php
        networks:
            - front
            - back
    php:
        build:
            context: ./images/php
        # cpu_count: 4
        cpu_percent: 0
        # cpus: 0.000
        cpu_shares: 0
        # cpuset: 0,3
        volumes:
            - ./logs/php:/var/log/php
            - ./logs/php/xdebug/:/var/log/php
            - ./web/html/php.ini.sample:/usr/local/etc/php/php.ini
            - ./config/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./config/php/conf.d/php.ini:/usr/local/etc/php/conf.d/docker-php-ext-error.ini
            - ./config/php/fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./config/php/bin/magento:/usr/local/bin/magento
            - ./web/html:/var/www/html
        depends_on:
            - database
            - cache
            - session
        user: www-data
        networks:
            - back

    database:
        image: percona:latest
        volumes:
            - database_data:/var/lib/mysql
            - ./dump:/dump
        environment:
            MYSQL_DATABASE: magento
            MYSQL_ROOT_PASSWORD: magento
            MYSQL_USER: magento
            MYSQL_PASSWORD: magento
        networks:
            - back

    cache:
        image: redis:alpine
        networks:
            - back
    session:
        image: redis:alpine
        networks:
            - back

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 8080:80
        environment:
            MYSQL_ROOT_PASSWORD: magento
            PMA_HOST: database
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: magento
        networks:
            - front
            - back
networks:
    front:
        driver: bridge
    back:
        driver: bridge
volumes:
    database_data:
        driver: local
